# 配置模版在线地址 https://gitee.com/lyhuilin/openAPI
# openAPI基本配置指南 https://www.yuque.com/docs/share/9bb68b8f-ff00-4dcd-93d0-be692e43213f
# 正确配置文件名为：config.yaml
#
# Server的名字
name: my_server
#
#
## 日志相关配置说明。
# writers: 输出位置，有2个可选项：file,stdout。选择file会将日志记录到logger_file指定的日志文件中，选择stdout会将日志输出到标准输出，当然也可以两者同时选择
# logger_level: 日志级别，DEBUG, INFO, WARN, ERROR, FATAL
# logger_file: 日志文件
# log_format_text: 日志的输出格式，json或者plaintext，true会输出成json格式，false会输出成非json格式
# rollingPolicy: rotate依据，可选的有：daily, size。如果选daily则根据天进行转存，如果是size则根据大小进行转存
# log_rotate_date: rotate转存时间，配合rollingPolicy: daily使用
# log_rotate_size: rotate转存大小，配合rollingPolicy: size使用
# log_backup_count:当日志文件达到转存标准时，log系统会将该日志文件进行压缩备份，这里指定了备份文件的最大个数。
# 日志相关配置。
log:
  writers: file,stdout
  logger_level: INFO
  logger_file: log/log.log
  log_format_text: false
  rollingPolicy: size
  log_rotate_date: 1
  log_rotate_size: 1
  log_backup_count: 7
#
